# .goreleaser.yml
# Build customization
project_name: butler
builds:
  - binary: butler
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
archive:
 files:
    - LICENSE.txt
    - README.md
    - CHANGELOG.md
    - docs/*
    - butler.yml